sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
    - 4
    - stable
env:
  - CHAI_VERSION=^2.1.2
  - CHAI_VERSION=^3.0.0
  - CHAI_VERSION=^4.0.0
script:
  - npm run lint
  - npm run test-travis
